version: '3.8'

services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              gunicorn myshop.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis:6.2.6-alpine
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  celery:
    build: .
    restart: always
    command: celery -A myshop worker -l info
    depends_on:
      - rabbitmq
    env_file:
      - ./.env

  stripe-cli:
    image: stripe/stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to web:8000/payment/webhook/"
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_value:
  media_value:
  redis_data: