# Generated by Django 4.1.2 on 2022-10-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("shop", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        )
    ]
